apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-poc
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/CHANGE_ME/REPO_NAME
    targetRevision: main
    path: deploy/helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rag-poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
